-- ============================================
-- AXIOMS - Auto ID Generation
-- ============================================
-- This script adds automatic ID generation for all entities
-- to prevent manual entry errors

-- 1. Create function to auto-generate product item codes
-- ============================================
CREATE OR REPLACE FUNCTION generate_product_item_code()
RETURNS TRIGGER AS $$
DECLARE
  max_code INTEGER;
  new_code TEXT;
BEGIN
  -- Only auto-generate if item_code is NULL or empty
  IF NEW.item_code IS NULL OR NEW.item_code = '' THEN
    -- Get the highest existing code number
    SELECT COALESCE(
      MAX(CAST(REGEXP_REPLACE(item_code, '[^0-9]', '', 'g') AS INTEGER)), 
      0
    )
    INTO max_code
    FROM products
    WHERE item_code ~ '^PRD[0-9]+$';
    
    -- Generate new code with format PRD0001, PRD0002, etc.
    new_code := 'PRD' || LPAD((max_code + 1)::TEXT, 4, '0');
    NEW.item_code := new_code;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2. Create trigger for auto-generating product item codes
-- ============================================
DROP TRIGGER IF EXISTS auto_generate_product_item_code ON products;

CREATE TRIGGER auto_generate_product_item_code
  BEFORE INSERT ON products
  FOR EACH ROW
  EXECUTE FUNCTION generate_product_item_code();

-- 3. Test the auto-generation
-- ============================================
-- Try inserting a product without item_code
-- INSERT INTO products (item_name, price, stock) 
-- VALUES ('Test Product', 1000.00, 10);
-- 
-- Check the auto-generated code:
-- SELECT item_code, item_name FROM products 
-- WHERE item_name = 'Test Product';

-- ============================================
-- NOTES:
-- ============================================
-- - UUIDs (id fields) are already auto-generated by PostgreSQL
-- - Product item_code will now auto-generate as PRD0001, PRD0002, etc.
-- - If you provide an item_code, it will be used instead
-- - Auto-generation happens at INSERT time
-- - The trigger ensures sequential codes starting from the highest existing code

-- ============================================
-- VERIFY AUTO-GENERATION
-- ============================================
SELECT 
  'products' as table_name,
  column_name,
  column_default,
  data_type
FROM information_schema.columns
WHERE table_name = 'products' 
  AND column_name = 'id';
-- Should show: uuid_generate_v4()

-- Verify trigger exists
SELECT 
  trigger_name,
  event_manipulation,
  event_object_table,
  action_statement
FROM information_schema.triggers
WHERE event_object_table = 'products'
  AND trigger_name = 'auto_generate_product_item_code';
-- Should show the trigger we just created

-- ============================================
-- SUMMARY OF AUTO-GENERATED IDs:
-- ============================================
-- ✅ products.id          → Auto UUID (uuid_generate_v4())
-- ✅ products.item_code   → Auto PRD0001, PRD0002... (new trigger)
-- ✅ customers.id         → Auto UUID (uuid_generate_v4())
-- ✅ orders.id            → Auto UUID (uuid_generate_v4())
-- ✅ order_items.id       → Auto UUID (uuid_generate_v4())
-- ✅ payments.id          → Auto UUID (uuid_generate_v4())
-- ✅ users.id             → Auto UUID (uuid_generate_v4())

-- NO MANUAL ID ENTRY REQUIRED! 🎉
